name: "Terraform Plan"

on:
  workflow_call:

env:
  AWS_REGION: "us-east-1" # Specify your AWS region
  TF_VAR_ecr_repository_name: "my-api-repo"
  TF_VAR_eks_cluster_name: "my-eks-cluster"
  TF_VAR_vpc_cidr: "10.0.0.0/16"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform/pipelines
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/pipelines
          terraform plan
